[tool.poetry]
name = "ke2daira"
version = "0.2.0"
description = "A Python implementaion of ke2daira"
authors = ["otariidae <otariidae@users.noreply.github.com>"]
license = "Apache-2.0"

homepage = "https://github.com/otariidae/ke2daira.py"
repository = "https://github.com/otariidae/ke2daira.py"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Janome = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^8.4"
black = "^24.3"
mypy = "^0.961"
ruff = "^0.0.284"

[tool.mypy]
strict = true

[tool.ruff]
select = ["ALL"]
ignore = ["D"]
target-version = "py39"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
